version: "3.7"


services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - gis_3ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gisp_static:/data/static/
      - gisp_media:/data/media/


  django:
    image: gis_3ban_django:4
    networks:
      - gis_3ban_network
    volumes :
      - gisp_static:/home/gis_3class/static/
      - gisp_media:/home/gis_3class/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_3ban_network
    volumes:
    - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: django
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django

networks:
  gis_3ban_network:

volumes:
  gisp_static:
  gisp_media:
  gis_mariadb: